---
title: "ST 538 Project 1 R Notebook"
author:
  - Di Chen
  - Mai Castellano
  - Tyler Kussee
  - Spencer Hutchison
output:
  pdf_document: default
  html_notebook: default
---

```{r echo=FALSE, message=FALSE}
## For your notes, an if statement for checking if a package is installed :)
#if(!require(somepackage)){
#    install.packages("somepackage")
#    library(somepackage)
#}

if (!require(tidycensus)) {
  install.packages("tidycensus")
}
if (!require(tidyverse)) {
  install.packages("tidyverse")
}
```


```{r echo=FALSE, message=FALSE}
library(tidycensus)
library(tidyverse)

census_api_key("2547c95ce33b1ed0eec3aafd0fd8526a5bb9a22e")
```



## Obtain the Data

```{r echo=FALSE, message=FALSE, results='hide'}
puma_data <- get_pums(variables = c("AGEP","SCHL","PINCP")
                      ,state = "OR"
                      ,year = 2022)
```

## Scrub the data

## Explore the data

[Reference on Variables for now](https://usa.ipums.org/usa/resources/codebooks/DataDict1822.pdf)

## Model the data

## Interpret the data
